<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>935ee010-5725-4f4d-a307-4f5ef83e89e0</UserSecretsId>
  </PropertyGroup>

 
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.2" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartStayBLL\SmartStayBLL.csproj" />
  </ItemGroup>

</Project>
