namespace SmartStayBLL
{
    public sealed class CreateStripePaymentIntentRequest
    {
        public Guid PaymentId { get; set; }

        public Guid BookingId { get; set; }

        public Guid GuestUserId { get; set; }

        public decimal Amount { get; set; }

        public string Currency { get; set; } =
            string.Empty;

        /*
         * This is the idempotency key sent to Stripe.
         *
         * It should be generated by the backend from
         * the local BookingPayment identifier.
         */
        public string ProviderIdempotencyKey { get; set; } =
            string.Empty;

        public DateTimeOffset? BookingExpiresAt { get; set; }
    }
}