namespace SmartStayDAL
{
    public sealed class BookingPayment
    {
        public Guid Id { get; set; }

        public Guid BookingId { get; set; }

        /*
         * Financial snapshot of the amount requested
         * from the payment provider.
         *
         * This must match Booking.TotalAmount when the
         * payment attempt is created.
         */
        public decimal Amount { get; set; }

        public string Currency { get; set; } =
            "EGP";

        /*
         * Examples:
         *
         * Paymob
         * Stripe
         * PayPal
         *
         * Keeping this as a string prevents the database
         * design from being coupled to one provider.
         */
        public string Provider { get; set; } =
            string.Empty;

        /*
         * Generated by SmartStay before communicating
         * with the payment provider.
         *
         * Repeating the same initiation request with the
         * same key must not create another payment attempt.
         */
        public string IdempotencyKey { get; set; } =
            string.Empty;

        /*
         * Identifier returned by the payment provider.
         *
         * For Stripe, this is the PaymentIntent ID.
         *
         * Example:
         *
         * pi_1...
         */
        public string? ProviderPaymentId { get; set; }

        /*
         * An additional provider reference.
         *
         * For Stripe, this currently stores the latest
         * Charge ID when it is available.
         *
         * Example:
         *
         * ch_1...
         */
        public string? ProviderReference { get; set; }

        public PaymentStatus Status { get; set; } =
            PaymentStatus.Pending;

        /*
         * Total amount successfully refunded so far
         * across all refund operations.
         *
         * It starts at zero and cannot exceed Amount.
         */
        public decimal RefundedAmount { get; set; }

        /*
         * Provider failure information for the original
         * payment attempt.
         */
        public string? FailureCode { get; set; }

        public string? FailureMessage { get; set; }

        public DateTimeOffset CreatedAt { get; set; }

        public DateTimeOffset? UpdatedAt { get; set; }

        public DateTimeOffset? SucceededAt { get; set; }

        public DateTimeOffset? FailedAt { get; set; }

        public DateTimeOffset? CancelledAt { get; set; }

        /*
         * Set when at least one successful refund has
         * been processed.
         */
        public DateTimeOffset? RefundedAt { get; set; }

        public Booking Booking { get; set; } =
            null!;

        /*
         * A payment can theoretically contain more than
         * one partial refund operation.
         *
         * SmartStay's guest-cancellation flow will normally
         * create only one refund, but the database model
         * remains capable of tracking provider adjustments
         * and future administrator refunds.
         */
        public ICollection<BookingPaymentRefund> Refunds
        { get; set; } =
            new List<BookingPaymentRefund>();
    }
}